import type { AnimationStyle, StylePreset } from "./types";

export const STYLE_PRESETS: Record<AnimationStyle, StylePreset> = {
  tunnel: {
    id: "tunnel",
    label: "Hyperspace",
    hint: "Radial from center",
    spawnMode: "tunnel",
    speedMul: 1.15,
    stretchMul: 1.25,
    spawnMul: 1.1,
    trailChance: 0.5,
    lifeMin: 0.4,
    lifeMax: 1.05,
    radialBias: 0.05,
    curveChance: 0.18,
    burstCount: 70,
    breathAmp: 0.08,
    breathHz: 0.45,
    defaultAngle: null,
    defaultSpread: null,
    hideMotion: true,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: null,
    palette: [
      { h: 192, s: 100, l: 80 },
      { h: 262, s: 95, l: 82 },
      { h: 210, s: 100, l: 88 },
      { h: 42, s: 100, l: 76 },
      { h: 300, s: 85, l: 78 },
    ],
  },
  streaks: {
    id: "streaks",
    label: "Classic",
    hint: "Directional streaks",
    spawnMode: "directional",
    speedMul: 1,
    stretchMul: 1,
    spawnMul: 1,
    trailChance: 0.42,
    lifeMin: 0.45,
    lifeMax: 1.15,
    radialBias: 0.22,
    curveChance: 0,
    burstCount: 40,
    breathAmp: 0.05,
    breathHz: 0.4,
    defaultAngle: 270,
    defaultSpread: 18,
    hideMotion: false,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: null,
    palette: [
      { h: 192, s: 100, l: 78 },
      { h: 262, s: 95, l: 80 },
      { h: 330, s: 92, l: 78 },
      { h: 42, s: 100, l: 74 },
      { h: 158, s: 88, l: 72 },
    ],
  },
  aurora: {
    id: "aurora",
    label: "Aurora",
    hint: "Soft curved glow",
    spawnMode: "directional",
    speedMul: 0.72,
    stretchMul: 0.85,
    spawnMul: 0.75,
    trailChance: 0.55,
    lifeMin: 0.7,
    lifeMax: 1.6,
    radialBias: 0.12,
    curveChance: 0.85,
    burstCount: 28,
    breathAmp: 0.14,
    breathHz: 0.35,
    defaultAngle: 270,
    defaultSpread: 32,
    hideMotion: false,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: null,
    palette: [
      { h: 158, s: 85, l: 68 },
      { h: 192, s: 90, l: 72 },
      { h: 280, s: 75, l: 74 },
      { h: 320, s: 70, l: 76 },
      { h: 175, s: 80, l: 70 },
    ],
  },
  rain: {
    id: "rain",
    label: "Neon rain",
    hint: "Dense downward rain",
    spawnMode: "directional",
    speedMul: 1.05,
    stretchMul: 0.7,
    spawnMul: 1.35,
    trailChance: 0.22,
    lifeMin: 0.35,
    lifeMax: 0.85,
    radialBias: 0.04,
    curveChance: 0.05,
    burstCount: 55,
    breathAmp: 0.04,
    breathHz: 0.55,
    defaultAngle: 90,
    defaultSpread: 10,
    hideMotion: false,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: null,
    palette: [
      { h: 150, s: 100, l: 62 },
      { h: 165, s: 95, l: 68 },
      { h: 130, s: 90, l: 58 },
      { h: 192, s: 80, l: 70 },
      { h: 100, s: 85, l: 60 },
    ],
  },
  embers: {
    id: "embers",
    label: "Embers",
    hint: "Warm rising sparks",
    spawnMode: "directional",
    speedMul: 0.55,
    stretchMul: 0.55,
    spawnMul: 0.85,
    trailChance: 0.35,
    lifeMin: 0.9,
    lifeMax: 1.9,
    radialBias: 0.08,
    curveChance: 0.35,
    burstCount: 35,
    breathAmp: 0.1,
    breathHz: 0.3,
    defaultAngle: 270,
    defaultSpread: 28,
    hideMotion: false,
    sizeGrow: true,
    sizeMul: 1.35,
    trailMaxPoints: 5,
    palette: [
      { h: 18, s: 100, l: 58 },
      { h: 32, s: 100, l: 55 },
      { h: 8, s: 95, l: 52 },
      { h: 42, s: 100, l: 62 },
      { h: 0, s: 90, l: 56 },
    ],
  },
  comet: {
    id: "comet",
    label: "Comet",
    hint: "Sparse long tails",
    spawnMode: "directional",
    speedMul: 0.9,
    stretchMul: 1.85,
    spawnMul: 0.28,
    trailChance: 1,
    lifeMin: 0.8,
    lifeMax: 1.6,
    radialBias: 0.06,
    curveChance: 0.12,
    burstCount: 10,
    breathAmp: 0.06,
    breathHz: 0.25,
    defaultAngle: 270,
    defaultSpread: 14,
    hideMotion: false,
    sizeGrow: false,
    sizeMul: 1.6,
    trailMaxPoints: 8,
    palette: [
      { h: 195, s: 100, l: 88 },
      { h: 210, s: 40, l: 95 },
      { h: 185, s: 90, l: 78 },
      { h: 230, s: 70, l: 85 },
      { h: 0, s: 0, l: 96 },
    ],
  },
  spark: {
    id: "spark",
    label: "Spark",
    hint: "Short bursts from points",
    spawnMode: "spark",
    speedMul: 1.2,
    stretchMul: 0.55,
    spawnMul: 1.4,
    trailChance: 0.15,
    lifeMin: 0.18,
    lifeMax: 0.45,
    radialBias: 0,
    curveChance: 0,
    burstCount: 60,
    breathAmp: 0.12,
    breathHz: 0.7,
    defaultAngle: null,
    defaultSpread: null,
    hideMotion: true,
    sizeGrow: false,
    sizeMul: 0.9,
    trailMaxPoints: 3,
    palette: [
      { h: 48, s: 100, l: 72 },
      { h: 0, s: 0, l: 98 },
      { h: 330, s: 90, l: 75 },
      { h: 28, s: 100, l: 68 },
      { h: 200, s: 80, l: 80 },
    ],
  },
  orbit: {
    id: "orbit",
    label: "Orbit",
    hint: "Rings around center",
    spawnMode: "orbital",
    speedMul: 0.85,
    stretchMul: 0.65,
    spawnMul: 0.95,
    trailChance: 0.55,
    lifeMin: 1.2,
    lifeMax: 2.4,
    radialBias: 0,
    curveChance: 0.4,
    burstCount: 45,
    breathAmp: 0.09,
    breathHz: 0.35,
    defaultAngle: null,
    defaultSpread: null,
    hideMotion: true,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: 6,
    palette: [
      { h: 262, s: 95, l: 78 },
      { h: 192, s: 100, l: 76 },
      { h: 280, s: 85, l: 80 },
      { h: 210, s: 90, l: 82 },
      { h: 300, s: 70, l: 78 },
    ],
  },
  vortex: {
    id: "vortex",
    label: "Vortex",
    hint: "Spiral out from center",
    spawnMode: "vortex",
    speedMul: 1.05,
    stretchMul: 1.1,
    spawnMul: 1.05,
    trailChance: 0.48,
    lifeMin: 0.55,
    lifeMax: 1.35,
    radialBias: 0,
    curveChance: 0.3,
    burstCount: 55,
    breathAmp: 0.08,
    breathHz: 0.5,
    defaultAngle: null,
    defaultSpread: null,
    hideMotion: true,
    sizeGrow: false,
    sizeMul: 1,
    trailMaxPoints: 5,
    palette: [
      { h: 280, s: 95, l: 72 },
      { h: 175, s: 90, l: 68 },
      { h: 300, s: 85, l: 70 },
      { h: 200, s: 100, l: 74 },
      { h: 320, s: 80, l: 76 },
    ],
  },
  datastream: {
    id: "datastream",
    label: "Datastream",
    hint: "Lane packets · data flow",
    spawnMode: "datastream",
    speedMul: 0.88,
    stretchMul: 0.65,
    spawnMul: 0.95,
    trailChance: 0.38,
    lifeMin: 0.5,
    lifeMax: 1.05,
    radialBias: 0,
    curveChance: 0,
    burstCount: 32,
    breathAmp: 0.03,
    breathHz: 0.4,
    defaultAngle: 0,
    defaultSpread: 6,
    hideMotion: false,
    sizeGrow: false,
    sizeMul: 0.62,
    trailMaxPoints: 3,
    glowDrawMul: 0.42,
    softBloom: true,
    palette: [
      { h: 196, s: 70, l: 58 },
      { h: 205, s: 55, l: 62 },
      { h: 188, s: 65, l: 54 },
      { h: 212, s: 40, l: 68 },
      { h: 200, s: 50, l: 56 },
    ],
  },
  signal: {
    id: "signal",
    label: "Signal",
    hint: "Concentric waves · ambient",
    spawnMode: "signal",
    speedMul: 0.68,
    stretchMul: 0.7,
    spawnMul: 0.78,
    trailChance: 0.38,
    lifeMin: 0.55,
    lifeMax: 1.25,
    radialBias: 0,
    curveChance: 0.1,
    burstCount: 36,
    breathAmp: 0.16,
    breathHz: 0.45,
    defaultAngle: null,
    defaultSpread: null,
    hideMotion: true,
    sizeGrow: false,
    sizeMul: 0.95,
    trailMaxPoints: 4,
    glowDrawMul: 1.05,
    softBloom: true,
    palette: [
      { h: 192, s: 100, l: 88 },
      { h: 255, s: 95, l: 90 },
      { h: 210, s: 90, l: 92 },
      { h: 280, s: 85, l: 88 },
      { h: 175, s: 95, l: 86 },
    ],
  },
};

export const STYLE_ORDER: AnimationStyle[] = [
  "tunnel",
  "signal",
  "streaks",
  "aurora",
  "rain",
  "embers",
  "comet",
  "spark",
  "orbit",
  "vortex",
  "datastream",
];

export function getStylePreset(id: AnimationStyle): StylePreset {
  return STYLE_PRESETS[id] ?? STYLE_PRESETS.tunnel;
}

export function isAnimationStyle(v: unknown): v is AnimationStyle {
  return (
    v === "tunnel" ||
    v === "streaks" ||
    v === "aurora" ||
    v === "rain" ||
    v === "embers" ||
    v === "comet" ||
    v === "spark" ||
    v === "orbit" ||
    v === "vortex" ||
    v === "datastream" ||
    v === "signal"
  );
}
